from random import seed

TRUCK_TYPES = {"zielona": 1000, "niebieska": 1500, "czerwona": 2000}

SEED = 10
POINTS_NUMBER = 100
WAREHOUSES_NUMBER = 5
CARGO_UPPER_POSITIVE_BOUNDARY = 200
CARGO_LOWER_POSITIVE_BOUNDARY = 100
CARGO_UPPER_NEGATIVE_BOUNDARY = -100
CARGO_LOWER_NEGATIVE_BOUNDARY = -200
BOARD_SIZE = 100
PRODUCTS = ("tuńczyk", "pomarańcze", "uran")

seed(SEED)
